header:
  - 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0 -BugBounty-'

exclude-tags: ssl
exclude-templates:
  - misconfiguration/http-missing-security-headers.yaml 
  - misconfiguration/xss-deprecated-header.yaml
  - dns/dmarc-detect.yaml
  - dns/nameserver-fingerprint.yaml

rate-limit: 500
bulk-size: 50
concurrency: 50
