name: Docker build and push

on: [push]

env:
  DOCKER_IMAGE: xanhacks/xanhunt 
  DOCKER_PUSH: github.ref == 'refs/heads/master'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      if: ${{ env.DOCKER_PUSH }} 
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ env.DOCKER_PUSH }}
        tags: ${{ env.DOCKER_IMAGE }}

